language: dart

dart:
  - 2.12.0

install:
  - pub get
  - gem install coveralls-lcov

script:
  pub run test_cov

after_success:
  - coveralls-lcov coverage/lcov.info

branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache