# Use the official Dart linter rules for Dart 3+
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
    - example/**
    - test/.test_coverage.dart
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    missing_required_param: error
    invalid_use_of_protected_member: error
    dead_code: info
    invalid_dependency: ignore  # Ignore 'path' deps in example

linter:
  rules:
    # === Best practices ===
    - always_declare_return_types
    - annotate_overrides
    - prefer_final_fields
    - prefer_const_constructors
    - prefer_conditional_assignment
    - prefer_null_aware_operators

    # === Naming and style ===
    - constant_identifier_names
    - lines_longer_than_80_chars
    - public_member_api_docs

    # === Code structure ===
    - one_member_abstracts
    - recursive_getters
    - null_closures
    - prefer_is_empty
    - prefer_is_not_empty
